site_name: 秋州发布
site_url: https://fabu.qiuzhou.sciograph.top/
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
